sudo: false

branches:
  only:
    - master
    - devel

language: node_js

cache:
  directories:
    - node_modules

env:
  matrix:
    - BUILD_SUBTASK=coverage
    - secure: bnLVOGfAIs3ljtPySWrWc89tGy10DWkS48BSI8uRt5fO/RVct6If9j8Y6Ec7Rd7ijFmEbzyOxZw2USeIVceFY1NuAISNfvCxwpryf+xIHcFddaYzMWFG07O1loXJLxDdELRZJ+5Z+bpLPL5eea3+QcoqxksSGF5Stkr+lMUuwF0=

script: bash travis.sh script
