sudo: false

branches:
  only:
    - master
    - devel

language: node_js

cache:
  directories:
    - node_modules

env:
  matrix:
    - COMMAND=browserstack
    - COMMAND=coverage

script: bash travis.sh $COMMAND
