sudo: false

branches:
  only:
    - master
    - devel

language: node_js

cache:
  directories:
    - node_modules

env:
  matrix:
    - BUILD_SUBTASK=browserstack
    - BUILD_SUBTASK=coverage

install: bash travis.sh install

script: bash travis.sh script
